services:
  mysql-test:
    image: mysql:8.0
    container_name: mysql-test-container
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_ROOT_PASSWORD: testpass
    ports:
      - '3307:3306'
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'testuser',
          '-ptestpass',
        ]
      interval: 5s
      timeout: 5s
      retries: 20
    command: --default-authentication-plugin=mysql_native_password
